### ISSUE TITLE
Reference documentation is missing

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-notebooks#19]
Looking at the failing CI, it looks like https://googleapis.dev/nodejs/notebooks/latest is coming up 404.  We've already published a 1.0 of this library, so it looks like something gummed up the works.  I see 2 ways of handling it:
- Maybe it was a blip, and we should just hammer `1.0.1` through and assume the docs get published
- Maybe there's a real problem, and we're not publishing ref docs 😱 

Either way, figured this one deserved a little attention.  I am marking this a P1 because the failing docs test is blocking other PRs from landing on the default branch.  If this is benign, feel free to downgrade.

**Comment by bcoe** [comment]
fixed, _for now_.
